# Load base image (conda - to install HUMAnN with conda)
FROM sphong/miniconda

# Create a conda environment for HUMAnN
RUN conda create -y -n humann -c biobakery -c bioconda -c conda-forge python=3.7 humann=3.7 

# Set the default directories for the database
RUN /bin/bash -c "source activate humann && conda run -n humann humann_config --update database_folders nucleotide /database/chocophlan"
RUN /bin/bash -c "source activate humann && conda run -n humann humann_config --update database_folders protein /database/uniref"
RUN /bin/bash -c "source activate humann && conda run -n humann humann_config --update database_folders utility_mapping /database/misc"

# Set working directory 
WORKDIR /data

# Set ENTRYPOINT 
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh 
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Set CMD 
CMD ["/bin/bash"]
